-- Schema definitions
CREATE TABLE IF NOT EXISTS modules (module_id INTEGER PRIMARY KEY, sequence INTEGER, title TEXT, phase TEXT);
CREATE TABLE IF NOT EXISTS lessons (id TEXT PRIMARY KEY, sequence INTEGER, title TEXT, tactical_concept TEXT, module_id INTEGER);
CREATE TABLE IF NOT EXISTS concepts (concept_id INTEGER PRIMARY KEY, term TEXT);
CREATE TABLE IF NOT EXISTS concept_relationships (source_concept_id INTEGER, target_concept_id INTEGER, relationship_type TEXT, logic_rationale TEXT);
CREATE TABLE IF NOT EXISTS document_concepts (document_title TEXT, concept_id INTEGER);
CREATE TABLE IF NOT EXISTS query_log (ip TEXT, query TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS config (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS banned_ips (ip TEXT PRIMARY KEY, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS threats (id INTEGER PRIMARY KEY, ip TEXT, pattern TEXT, confidence REAL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);

-- Clear existing data
DELETE FROM modules;
DELETE FROM lessons;
DELETE FROM concepts;
DELETE FROM concept_relationships;
DELETE FROM document_concepts;
DELETE FROM query_log;
DELETE FROM config;
DELETE FROM banned_ips;
DELETE FROM threats;
INSERT INTO config (key, value) VALUES ('api_enabled', '1');
INSERT INTO modules (module_id, sequence, title, phase) VALUES (1, 1, 'Hybrid Warfare Fundamentals', 'DOCTRINE');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L01', 1, 'The Gerasimov Doctrine', 'Non-Linear Warfare', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L02', 2, 'The Gray Zone', 'Sub-Threshold Aggression', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L03', 3, 'Reflexive Control', 'Decision Shaping', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L04', 4, 'Plausible Deniability', 'Legal Cut-Outs', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L05', 5, 'Information Dominance', 'Narrative Supremacy', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L06', 6, 'Attribution Decay', 'Cyber-Obfuscation', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L07', 7, 'The Proxy Economy', 'Outsourced Violence', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L08', 8, 'Salami Slicing', 'Incremental Gain', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L09', 9, 'Lawfare Architecture', 'Legal Paralysis', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L10', 10, 'Systemic Destabilization', 'Infrastructure Targeting', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L11', 11, 'Strategic Parity', 'Asymmetric Balancing', 1);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L12', 12, 'Total vs. Limited War', 'Objective Scoping', 1);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (2, 2, 'The Intelligence Preparation of the Battlespace', 'DOCTRINE');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L13', 13, 'IPB Fundamentals', 'Terrain Mapping', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L14', 14, 'The Recruitment Cycle', 'Spot-Assess-Develop-Recruit', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L15', 15, 'M.I.C.E. Framework', 'Leverage Points', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L16', 16, 'The Soft Probe', 'Boundary Testing', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L17', 17, 'Vulnerability Assessment', 'The Hook', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L18', 18, 'Rapport-as-Weapon', 'Artificial Intimacy', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L19', 19, 'False Flag Recruitment', 'Deceptive Alignment', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L20', 20, 'Elicitation Protocols', 'Information Extraction', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L21', 21, 'Surveillance Detection', 'Counter-Observation', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L22', 22, 'Kompromat Generation', 'Sexual Entrapment', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L23', 23, 'Asset Validation', 'Reliability Testing', 2);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L24', 24, 'Termination & Burn', 'Asset Disposal', 2);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (3, 3, 'Network Topology & C2 Mirroring', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L25', 25, 'The Plaza System', 'Territorial Command', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L26', 26, 'Radio Zetas', 'Encrypted Comms Infrastructure', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L27', 27, 'The Cut-Out Structure', 'Insulated Leadership', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L28', 28, 'Compartmentalization', 'Need-to-Know', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L29', 29, 'The Halcon Network', 'Human Sensor Array', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L30', 30, 'Redundant Logistics', 'Supply Chain Resilience', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L31', 31, 'Dead Drops & Couriers', 'Physical Info Transfer', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L32', 32, 'The Sicario Cell', 'Special Forces Unit', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L33', 33, 'Fail-Safe Protocols', 'Capture contingencies', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L34', 34, 'Counter-Infiltration', 'Mole Hunting', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L35', 35, 'Digital Exhaust Control', 'Metadata Management', 3);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L36', 36, 'Shadow Governance', 'State Replacement', 3);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (4, 4, 'The Economics of Coercion', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L37', 37, 'The Laundromat', 'Layering & Integration', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L38', 38, 'Trade-Based Laundering', 'Value Transfer', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L39', 39, 'The Hawala Mirror', 'Trust-Based Transfer', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L40', 40, 'Crypto-Obfuscation', 'Digital Ledger Evasion', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L41', 41, 'Shell Company Architecture', 'Legal Shielding', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L42', 42, 'The Extortion Tax', 'Parallel Taxation', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L43', 43, 'Resource Capture', 'Strategic Asset Seizure', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L44', 44, 'Human Capital Weaponization', 'Forced Labor', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L45', 45, 'Corruption as Budget', 'Institutional Bribery', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L46', 46, 'The Narco-Subs', 'Stealth Logistics', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L47', 47, 'Real Estate Integration', 'Asset Parking', 4);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L48', 48, 'Franchise Models', 'Decentralized Expansion', 4);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (5, 5, 'Information Operations & Propaganda', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L49', 49, 'The Narco-Banner', 'Public Messaging', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L50', 50, 'The Gore Video', 'Terror Broadcasting', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L51', 51, 'Narcocorridos', 'Cultural Myth-Making', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L52', 52, 'Social Media Influencing', 'Recruitment Propaganda', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L53', 53, 'Journalist Intimidation', 'Censorship', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L54', 54, 'Disinformation Flooding', 'Noise Generation', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L55', 55, 'The ', 'Legitimacy Building', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L56', 56, 'Attribution Denial', 'False Flag Violence', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L57', 57, 'Signal Signaling', 'In-Group Verification', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L58', 58, 'Community ''Despensas''', 'Aid Diplomacy', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L59', 59, 'The Whisper Campaign', 'Rumor Propagation', 5);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L60', 60, 'Strategic Silence', 'Ambiguity', 5);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (6, 6, 'Surveillance & Counter-Surveillance', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L61', 61, 'The Halcon System', 'Static Surveillance', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L62', 62, 'Follow Teams', 'Mobile Surveillance', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L63', 63, 'Technical Intercepts', 'Cloned Phones/Stingrays', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L64', 64, 'Counter-Surveillance Drills', 'Heat Checks', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L65', 65, 'The Taxi Network', 'Ubiquitous Eyes', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L66', 66, 'Drone Usage', 'Aerial Reconnaissance', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L67', 67, 'Checkpoint Operations', 'Area Denial/Monitoring', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L68', 68, 'License Plate Logging', 'Pattern of Life Analysis', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L69', 69, 'Infiltration/Moles', 'Human Penetration', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L70', 70, 'GPS Tracking', 'Asset Tagging', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L71', 71, 'Open Source Intelligence', 'Social Media Scraping', 6);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L72', 72, 'Interrogation Protocol', 'Humint Extraction', 6);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (7, 7, 'Paramilitary & Proxy Dynamics', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L73', 73, 'The GAFE Lineage', 'Special Forces Desertion', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L74', 74, 'Technical Vehicles', 'Mobile Firepower', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L75', 75, 'Urban Combat Doctrine', 'CQB Tactics', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L76', 76, 'Proxy Gangs', 'Deniable Forces', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L77', 77, 'Ambush Tactics', 'Asymmetric Engagement', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L78', 78, 'The ''Monstros'' (Armored Trucks)', 'Force Projection', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L79', 79, 'Kidnap & Ransom', 'Resource Extraction', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L80', 80, 'Targeted Assassination', 'HVT Elimination', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L81', 81, 'Territorial Cleansing', 'Displacement', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L82', 82, 'Weapons Trafficking', 'Logistical Support', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L83', 83, 'IED Deployment', 'Area Denial', 7);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L84', 84, 'Training Camps', 'Force Generation', 7);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (8, 8, 'Institutional Co-option & State Capture', 'REFLECTION');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L85', 85, 'Plata o Plomo', 'Coercive Diplomacy', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L86', 86, 'The Police Payroll', 'Insider Threat', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L87', 87, 'Judicial Corruption', 'Lawfare Defense', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L88', 88, 'Political Campaign Funding', 'State Capture', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L89', 89, 'Prison Control', 'Forward Command Posts', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L90', 90, 'Regulatory Capture', 'Market Manipulation', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L91', 91, 'Border Corruption', 'Gateway Control', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L92', 92, 'Military Integration', 'Force Multipliers', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L93', 93, 'Infrastructure Theft', 'Resource Leeching', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L94', 94, 'Sanctuary Cities', 'Safe Havens', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L95', 95, 'The ''Narcopolitician''', 'Hybrid Actor', 8);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L96', 96, 'Impunity Architecture', 'Legal Immunity', 8);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (9, 9, 'Advanced Persistent Threats (Cyber & Cognitive)', 'ENDGAME');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L97', 97, 'Zero-Day Exploits', 'Strategic Cyber Weapons', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L98', 98, 'Sovereign Internets', 'Information Autarky', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L99', 99, 'Cognitive Domain Ops', 'Neuro-Strike', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L100', 100, 'Critical Infrastructure Kill Switches', 'Deterrence via Denial', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L101', 101, 'Global Surveillance Dragnets', 'Total Information Awareness', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L102', 102, 'Algorithmic Warfare', 'AI Battlefield Management', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L103', 103, 'Deepfake Diplomacy', 'Synthetic Reality', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L104', 104, 'Supply Chain Injection', 'Hardware Backdoors', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L105', 105, 'Satellite Warfare', 'Space Domain Denial', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L106', 106, 'Quantum Decryption', 'The Apocalypse Protocol', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L107', 107, 'Biometric Control', 'Identity Lock', 9);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L108', 108, 'The splinternet', 'Digital Balkanization', 9);
INSERT INTO modules (module_id, sequence, title, phase) VALUES (10, 10, 'Strategic Endgames & Total Control', 'ENDGAME');
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L109', 109, 'Mutually Assured Destruction', 'Ultimate Deterrence', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L110', 110, 'Sphere of Influence', 'Geopolitical Control', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L111', 111, 'Regime Change Operations', 'Political Engineering', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L112', 112, 'Economic Sanctions Regimes', 'Financial Siege Warfare', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L113', 113, 'The Security Dilemma', 'Escalation Spirals', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L114', 114, 'Grand Strategy', 'Long-Term Planning', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L115', 115, 'Failed States', 'Strategic Vacuums', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L116', 116, 'The Thucydides Trap', 'Hegemonic Transition', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L117', 117, 'Resource Wars', 'Survival Economics', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L118', 118, 'Ideological Subversion', 'Cultural Hegemony', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L119', 119, 'The Panopticon State', 'Total Social Control', 10);
INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('L120', 120, 'The Post-Westphalian Order', 'Future Sovereignty', 10);
