
import json
import os
import sys

def sync():
    # Adjusted to run from backend/scripts/ or root
    root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
    full_data_path = os.path.join(root_path, 'backend/data/curriculum_full.json')
    
    # If curriculum_full.json doesn't exist, we might need to generate it first
    # but for now we assume it was generated by the exporter script or exists.
    if not os.path.exists(full_data_path):
        print(f"Error: {full_data_path} not found. Ensure you've exported the curriculum to JSON first.")
        return

    with open(full_data_path, 'r') as f:
        modules_data = json.load(f)

    flat_lessons = []
    sql_statements = []

    # Table definitions
    sql_statements.append("-- Schema definitions")
    sql_statements.append("CREATE TABLE IF NOT EXISTS modules (module_id INTEGER PRIMARY KEY, sequence INTEGER, title TEXT, phase TEXT);")
    sql_statements.append("CREATE TABLE IF NOT EXISTS lessons (id TEXT PRIMARY KEY, sequence INTEGER, title TEXT, tactical_concept TEXT, module_id INTEGER);")
    sql_statements.append("CREATE TABLE IF NOT EXISTS concepts (concept_id INTEGER PRIMARY KEY, term TEXT);")
    sql_statements.append("CREATE TABLE IF NOT EXISTS concept_relationships (source_concept_id INTEGER, target_concept_id INTEGER, relationship_type TEXT, logic_rationale TEXT);")
    sql_statements.append("CREATE TABLE IF NOT EXISTS document_concepts (document_title TEXT, concept_id INTEGER);")
    sql_statements.append("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, applied_at DATETIME DEFAULT CURRENT_TIMESTAMP);")
    
    sql_statements.append("\n-- Clear existing data")
    sql_statements.append("DELETE FROM modules;")
    sql_statements.append("DELETE FROM lessons;")
    sql_statements.append("DELETE FROM concepts;")
    sql_statements.append("DELETE FROM concept_relationships;")
    sql_statements.append("DELETE FROM document_concepts;")
    
    sql_statements.append("\n-- Versioning")
    sql_statements.append("INSERT OR IGNORE INTO schema_version (version) VALUES (1);")

    for m_idx, module in enumerate(modules_data, 1):
        module_id = m_idx
        m_title = module['title'].replace("'", "''")
        m_phase = module['phase']
        m_seq = module['sequence']
        sql_statements.append(f"INSERT INTO modules (module_id, sequence, title, phase) VALUES ({module_id}, {m_seq}, '{m_title}', '{m_phase}');")
        
        for lesson in module['lessons']:
            try:
                seq = int(lesson['id'][1:])
            except:
                seq = 0
            
            flat_lesson = {
                "id": lesson['id'],
                "title": lesson['title'],
                "tacticalConcept": lesson['tacticalConcept'],
                "historicalValidator": lesson['historicalValidator'],
                "phase": module['phase'],
                "moduleId": module_id
            }
            flat_lessons.append(flat_lesson)
            
            l_title = lesson['title'].replace("'", "''")
            l_concept = lesson['tacticalConcept'].replace("'", "''")
            sql_statements.append(f"INSERT INTO lessons (id, sequence, title, tactical_concept, module_id) VALUES ('{lesson['id']}', {seq}, '{l_title}', '{l_concept}', {module_id});")

    # Save flattened curriculum for embedding script
    output_json_path = os.path.join(root_path, 'backend/data/curriculum.json')
    output_json = {"lessons": flat_lessons}
    with open(output_json_path, 'w') as f:
        json.dump(output_json, f, indent=2)
    
    # Save SQL seed
    seed_sql_path = os.path.join(root_path, 'backend/data/seed.sql')
    with open(seed_sql_path, 'w') as f:
        f.write("\n".join(sql_statements) + "\n")

    print(f"Successfully synced {len(flat_lessons)} lessons across {len(modules_data)} modules.")
    print(f"Generated {output_json_path} and {seed_sql_path}")

if __name__ == "__main__":
    sync()
